<a href="https://colab.research.google.com/github/25071001-ai/data_science/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2],[3,4]])
print(arr1)

[[1 2]
 [3 4]]


In [3]:
arr2=np.random.rand(3,4)
print(arr2)

[[0.17632236 0.76325909 0.96939891 0.16044383]
 [0.81244469 0.09037704 0.54723102 0.0362829 ]
 [0.54210694 0.89438726 0.50908018 0.76069336]]


In [4]:
ones=np.ones((2,3))
zeros=np.zeros((2,3))
print(ones)
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr3=np.random.rand(6,3)
print(arr3)
print(arr3.T)

[[0.62186962 0.82594348 0.64341087]
 [0.76461937 0.85091995 0.72432967]
 [0.06083892 0.51308035 0.85925569]
 [0.79613878 0.34777893 0.19246875]
 [0.00314758 0.17073119 0.67556399]
 [0.83867062 0.30359918 0.49231598]]
[[0.62186962 0.76461937 0.06083892 0.79613878 0.00314758 0.83867062]
 [0.82594348 0.85091995 0.51308035 0.34777893 0.17073119 0.30359918]
 [0.64341087 0.72432967 0.85925569 0.19246875 0.67556399 0.49231598]]


In [6]:
A=np.random.rand(2,3)
B=np.random.rand(3,4)
print(A)
print(B)
dot_product=np.dot(A,B)
print(dot_product)

[[0.63246162 0.56810522 0.3176256 ]
 [0.59466377 0.49385626 0.49253728]]
[[0.91658688 0.97922012 0.85378136 0.03597565]
 [0.10356901 0.04106447 0.84465689 0.8681849 ]
 [0.79171699 0.9167463  0.80906309 0.80859864]]
[[0.8900137  0.93383018 1.27681708 0.77280522]
 [0.98615935 1.05411841 1.32334568 0.84841694]]
